export const SET_FROM_COORDS = "SET_FROM_COORDS";
export const SET_TO_COORDS = "SET_TO_COORDS";
export const CLEAR_FROM_COORDS = "CLEAR_FROM_COORDS";
export const CLEAR_TO_COORDS = "CLEAR_TO_COORDS";

export const SET_FROM_ADDRESS = "SET_FROM_ADDRESS";
export const SET_TO_ADDRESS = "SET_TO_ADDRESS";
export const CLEAR_FROM_ADDRESS = "CLEAR_FROM_ADDRESS";
export const CLEAR_TO_ADDRESS = "CLEAR_TO_ADDRESS";

export const FETCH_SUGGESTIONS_START = "FETCH_SUGGESTIONS_START";
export const FETCH_SUGGESTIONS_SUCCESS = "FETCH_SUGGESTIONS_SUCCESS";
export const FETCH_SUGGESTIONS_FAIL = "FETCH_SUGGESTIONS_FAIL";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";

export const SET_SELECTED_SUGGESTION = "SET_SELECTED_SUGGESTION";
export const CLEAR_SELECTED_SUGGESTION = "CLEAR_SELECTED_SUGGESTION";
