export const SET_FROM_COORDS = "SET_FROM_COORDS";
export const SET_TO_COORDS = "SET_TO_COORDS";
export const SET_FROM_ADDRESS = "SET_FROM_ADDRESS";
export const SET_TO_ADDRESS = "SET_TO_ADDRESS";
export const CLEAR_JOURNEY = "CLEAR_JOURNEY";

export const FETCH_SUGGESTIONS_START = "FETCH_SUGGESTIONS_START";
export const FETCH_SUGGESTIONS_SUCCESS = "FETCH_SUGGESTIONS_SUCCESS";
export const FETCH_SUGGESTIONS_FAIL = "FETCH_SUGGESTIONS_FAIL";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";

export const SET_SELECTED_TRIP = "SET_SELECTED_TRIP";
export const CLEAR_SELECTED_TRIP = "CLEAR_SELECTED_TRIP";
