export const SET_FROM_LOCATION = "SET_FROM_LOCATION";
export const SET_TO_LOCATION = "SET_TO_LOCATION";
export const CLEAR_FROM_LOCATION = "CLEAR_FROM_LOCATION";
export const CLEAR_TO_LOCATION = "CLEAR_TO_LOCATION";

export const FETCH_SUGGESTIONS_START = "FETCH_SUGGESTIONS_START";
export const FETCH_SUGGESTIONS_SUCCESS = "FETCH_SUGGESTIONS_SUCCESS";
export const FETCH_SUGGESTIONS_FAIL = "FETCH_SUGGESTIONS_FAIL";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";

export const SET_SELECTED_SUGGESTION = "SET_SELECTED_SUGGESTION";
export const CLEAR_SELECTED_SUGGESTION = "CLEAR_SELECTED_SUGGESTION";
